name: Certbot Renewal

# on:
#   schedule:
#     - cron: '15 4 * * *'

on:
  workflow_run:
    workflows: ["Deploy to AWS EC2"]
    types:
      - completed

jobs:
  renew-ssl-certificates:
    runs-on: ubuntu-latest

    steps:
    - name: Extract IP address from artifact
      run: |
        echo $PUB_IP
        echo "${PUBLIC_IP}"

    - name: Setup Nginx Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          set -e
          sudo certbot renew

          