name: Certbot Renewal

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  renew-ssl-certificates:
    runs-on: ubuntu-latest

    steps:
    - name: Extract IP address from artifact
      run: |
        public_ip=54.183.74.234
        echo "PUBLIC_IP=$public_ip" >> $GITHUB_ENV

    - name: Setup Nginx Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          set -e
          sudo certbot renew

          