name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker build -t your-docker-image-name .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-docker-image-name

    # - name: Deploy to AWS EC2
    #   run: |
    #     ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@your-ec2-instance-ip "docker pull your-docker-image-name && docker run -d -p 80:80 your-docker-image-name"
