name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        cd pas-website
        docker build -t pas-website .
        docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
        docker push pas-website

    - name: Deploy to AWS EC2
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ec2_ssh_key.pem
          chmod 400 ec2_ssh_key.pem
          ssh -i ec2_ssh_key.pem ec2-user@54.183.131.59 "docker pull pas-website && docker run -d -p 80:3000 pas-website"
