name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Docker
    #   run: |
    #     cd pas-website
    #     docker build . --tag ghcr.io/peakaltitudestudio/pas-website-ghrc:latest
    #     docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
    #     docker push ghcr.io/peakaltitudestudio/pas-website-ghrc:latest

    - name: Create known_hosts file
      run: |
        ls
        mkdir -p /home/runner/.ssh
        touch /home/runner/.ssh/known_hosts


    - name: Deploy to AWS EC2
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ec2sshkeypair.pem
        chmod 400 ec2sshkeypair.pem
        ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/home/runner/.ssh/known_hosts \
          -i ec2sshkeypair.pem \
          ec2-user@18.144.54.243 <<EOF
          container_id=$(docker ps -q)
          echo $container_id
          if [ -n "$container_id" ]; then
            echo "Inside if"
            docker kill $container_id || true
          fi
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker pull ghcr.io/peakaltitudestudio/pas-website-ghrc:latest
          docker run -d -p 3000:3000 ghcr.io/peakaltitudestudio/pas-website-ghrc
          EOF




