name: Delete Feature Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR status
        uses: actions/github-script@v4
        with:
          script: |
            const baseBranch = github.event.pull_request.base.ref;
            console.log("Base branch: " + baseBranch)
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Delete Branch
    #     if: steps.pr.outputs.PR !== 'PR is merged into a protected branch'
    #     run: |
    #       git fetch --prune
    #       git push --delete origin ${{ github.event.pull_request.head.ref }}
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
