name: Delete Feature Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  check-delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status
        run: |
          baseBranch="${{ github.event.pull_request.base.ref }}"
          headBranch="${{ github.event.pull_request.head.ref }}"
          echo "$headBranch was merged into $baseBranch"
          shouldDelete=false
          if [ "$headBranch" == "main" ] && [ "$headBranch" == "dev" ]; then
            echo "$headBranch is a protected branch and will not be deleted"
            echo "shouldDelete=false" >> $GITHUB_ENV
          else
            echo "Proceeding with deleting branch: $headBranch"
            echo "shouldDelete=true" >> $GITHUB_ENV
          fi

  delete-branch:
    runs-on: ubuntu-latest
    needs: check-delete-branch
    if: ${{ vars.shouldDelete == true }} 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
  
    #   - name: Configure AWS Usage
    #     if: ${{ env.shouldDelete }} == true
    #     run: |
    #       aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
    #   - name: Delete Branch
    #     if: ${{ env.shouldDelete }} == true
    #     run: |
    #       echo "Running the branch deletion for branch: ${{ github.event.pull_request.head.ref }}"
    #       git fetch --prune
    #       env:
    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
