name: Delete Feature Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  check-delete-branch:
    runs-on: ubuntu-latest
    outputs:
      shouldDelete: ${{ steps.check.outputs.shouldDelete }}
    steps:
      - name: Check PR status
        id: check
        run: |
          baseBranch="${{ github.event.pull_request.base.ref }}"
          headBranch="${{ github.event.pull_request.head.ref }}"
          echo "$headBranch was merged into $baseBranch"
          if [ "$headBranch" == "main" ] || [ "$headBranch" == "dev" ]; then
            echo "$headBranch is a protected branch and will not be deleted"
            echo "shouldDelete=false" >> $GITHUB_OUTPUT
          else
            echo "Proceeding with deleting branch: $headBranch"
            echo "shouldDelete=true" >> $GITHUB_OUTPUT
          fi
    

  delete-branch:
    runs-on: ubuntu-latest
    needs: check-delete-branch
    if: needs.check-delete-branch.outputs.shouldDelete == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
  
      - name: Configure AWS Usage
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Destroy Branch Terraform
        run: |
          ls
  
      - name: Delete Branch
        run: |
          echo "Running the branch deletion for branch: ${{ github.event.pull_request.head.ref }}"
          git fetch --prune
          git push --delete origin ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
