name: Delete Feature Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR status
        run: |
          baseBranch="${{ github.event.pull_request.base.ref }}"
          echo "Base branch: $baseBranch"
          headBranch="${{ github.event.pull_request.head.ref }}"
          echo "Head branch: $headBranch"

    #   - name: Delete Branch
    #     if: steps.pr.outputs.PR !== 'PR is merged into a protected branch'
    #     run: |
    #       git fetch --prune
    #       git push --delete origin ${{ github.event.pull_request.head.ref }}
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
